"""
exporters.py
------------
Exports RedistributionResult to CSV, HTML, and DOCX.
All files written to ./output/ by default.
"""

from __future__ import annotations

import csv
import os
from typing import List, Optional

from models import Module, RedistributionResult

OUTPUT_DIR = "output"


def _ensure_output_dir(output_dir: str = OUTPUT_DIR) -> str:
    os.makedirs(output_dir, exist_ok=True)
    return output_dir


# ---------------------------------------------------------------------------
# CSV
# ---------------------------------------------------------------------------

def export_csv(
    result: RedistributionResult,
    path: Optional[str] = None,
    output_dir: str = OUTPUT_DIR,
) -> str:
    out = path or os.path.join(_ensure_output_dir(output_dir), "recalibrated_syllabus.csv")
    rows = []
    for orig, recal in zip(
        sorted(result.original_modules, key=lambda m: m.module_id),
        sorted(result.recalibrated_modules, key=lambda m: m.module_id),
    ):
        delta = recal.allocated_hours - orig.original_hours
        rows.append({
            "Module ID":        orig.module_id,
            "Module Name":      orig.module_name,
            "Original Hours":   orig.original_hours,
            "Recalibrated Hours": recal.allocated_hours,
            "Delta (h)":        f"{delta:+.2f}",
            "PYQ Score":        f"{orig.pyq_score:.4f}",
            "Book Weight":      orig.book_weight,
            "Difficulty":       recal.difficulty.value,
            "Importance":       recal.importance.value,
            "Topics":           "; ".join(orig.topics),
        })

    with open(out, "w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=rows[0].keys())
        writer.writeheader()
        writer.writerows(rows)

    print(f"[exporter] CSV → {out}")
    return out


# ---------------------------------------------------------------------------
# HTML
# ---------------------------------------------------------------------------

_HTML_TEMPLATE = """\
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Recalibrated Syllabus</title>
<style>
  body {{ font-family: 'Segoe UI', Arial, sans-serif; margin: 40px; color: #1a1a2e; background: #f8f9fc; }}
  h1   {{ color: #16213e; border-bottom: 3px solid #0f3460; padding-bottom: 8px; }}
  h2   {{ color: #0f3460; margin-top: 32px; }}
  table {{ border-collapse: collapse; width: 100%; margin-top: 16px; background: #fff;
           box-shadow: 0 2px 8px rgba(0,0,0,0.08); border-radius: 8px; overflow: hidden; }}
  th   {{ background: #0f3460; color: #fff; padding: 12px 14px; text-align: left; font-size: 0.9em; }}
  td   {{ padding: 10px 14px; border-bottom: 1px solid #e8ecf0; font-size: 0.88em; }}
  tr:last-child td {{ border-bottom: none; }}
  tr:hover td {{ background: #eef2f7; }}
  .pos {{ color: #2d6a4f; font-weight: 600; }}
  .neg {{ color: #c0392b; font-weight: 600; }}
  .zero {{ color: #7f8c8d; }}
  .warn {{ background: #fff3cd; border-left: 4px solid #f0a500; padding: 10px 14px;
           margin: 8px 0; border-radius: 4px; font-size: 0.85em; }}
  .log  {{ background: #e8f4fd; border-left: 4px solid #2980b9; padding: 10px 14px;
           margin: 8px 0; border-radius: 4px; font-size: 0.82em; font-family: monospace; }}
  .narrative {{ background: #fff; padding: 20px 24px; border-radius: 8px;
                box-shadow: 0 2px 8px rgba(0,0,0,0.06); line-height: 1.7; }}
  .total-row td {{ font-weight: 700; background: #eef2f7; }}
  footer {{ margin-top: 40px; font-size: 0.78em; color: #aaa; }}
</style>
</head>
<body>
<h1>Adaptive Syllabus Recalibration Report</h1>

<h2>Recalibrated Module Hours</h2>
<table>
<thead>
<tr>
  <th>#</th>
  <th>Module</th>
  <th>Original (h)</th>
  <th>Recalibrated (h)</th>
  <th>Delta</th>
  <th>PYQ Score</th>
  <th>Difficulty</th>
  <th>Importance</th>
</tr>
</thead>
<tbody>
{rows}
<tr class="total-row">
  <td colspan="2">TOTAL</td>
  <td>{total_orig:.2f}h</td>
  <td>{total_recal:.2f}h</td>
  <td>—</td>
  <td colspan="3"></td>
</tr>
</tbody>
</table>

{narrative_section}

{warnings_section}

{log_section}

<footer>Generated by Adaptive Syllabus Recalibration Engine · System 2</footer>
</body>
</html>
"""


def export_html(
    result: RedistributionResult,
    narrative: str = "",
    path: Optional[str] = None,
    output_dir: str = OUTPUT_DIR,
) -> str:
    out = path or os.path.join(_ensure_output_dir(output_dir), "recalibrated_syllabus.html")

    orig_sorted  = sorted(result.original_modules,     key=lambda m: m.module_id)
    recal_sorted = sorted(result.recalibrated_modules, key=lambda m: m.module_id)

    row_html = ""
    total_orig  = 0.0
    total_recal = 0.0

    for orig, recal in zip(orig_sorted, recal_sorted):
        delta = recal.allocated_hours - orig.original_hours
        total_orig  += orig.original_hours
        total_recal += recal.allocated_hours

        if delta > 0.01:
            delta_str = f'<span class="pos">+{delta:.2f}h</span>'
        elif delta < -0.01:
            delta_str = f'<span class="neg">{delta:.2f}h</span>'
        else:
            delta_str = f'<span class="zero">—</span>'

        row_html += (
            f"<tr>"
            f"<td>{orig.module_id}</td>"
            f"<td><strong>{orig.module_name}</strong><br>"
            f"<small style='color:#666'>{'; '.join(orig.topics)}</small></td>"
            f"<td>{orig.original_hours:.2f}h</td>"
            f"<td>{recal.allocated_hours:.2f}h</td>"
            f"<td>{delta_str}</td>"
            f"<td>{orig.pyq_score:.4f}</td>"
            f"<td>{recal.difficulty.value}</td>"
            f"<td>{recal.importance.value}</td>"
            f"</tr>\n"
        )

    narrative_section = ""
    if narrative:
        narrative_section = (
            f"<h2>Summary</h2>"
            f'<div class="narrative">{narrative}</div>'
        )

    warnings_section = ""
    if result.warnings:
        warns = "".join(f'<div class="warn">⚠ {w}</div>' for w in result.warnings)
        warnings_section = f"<h2>Warnings</h2>{warns}"

    log_section = ""
    if result.adjustment_log:
        logs = "".join(f'<div class="log">{l}</div>' for l in result.adjustment_log)
        log_section = f"<h2>Adjustment Log</h2>{logs}"

    html = _HTML_TEMPLATE.format(
        rows=row_html,
        total_orig=total_orig,
        total_recal=total_recal,
        narrative_section=narrative_section,
        warnings_section=warnings_section,
        log_section=log_section,
    )

    with open(out, "w", encoding="utf-8") as f:
        f.write(html)

    print(f"[exporter] HTML → {out}")
    return out

def export_pdf(
    result: RedistributionResult,
    narrative: str = "",
    path: Optional[str] = None,
    output_dir: str = OUTPUT_DIR,
) -> str:
    try:
        from fpdf import FPDF
    except ImportError:
        raise ImportError("fpdf2 is required: pip install fpdf2")

    out = path or os.path.join(_ensure_output_dir(output_dir), "recalibrated_syllabus.pdf")

    pdf = FPDF()
    pdf.add_page()

    # Title
    pdf.set_font("Helvetica", "B", 16)
    pdf.cell(0, 10, "Adaptive Syllabus Recalibration Report", ln=True, align="C")
    pdf.ln(5)

    # Narrative
    if narrative:
        pdf.set_font("Helvetica", "B", 12)
        pdf.cell(0, 8, "Summary", ln=True)
        pdf.set_font("Helvetica", "", 10)
        pdf.multi_cell(0, 6, narrative)
        pdf.ln(4)

    # Table header
    pdf.set_font("Helvetica", "B", 10)
    pdf.set_fill_color(15, 52, 96)
    pdf.set_text_color(255, 255, 255)
    col_widths = [10, 52, 22, 28, 18, 22, 20, 22]
    headers = ["#", "Module", "Old (h)", "New (h)", "Delta", "PYQ", "Diff", "Importance"]
    for w, h in zip(col_widths, headers):
        pdf.cell(w, 8, h, border=1, fill=True)
    pdf.ln()

    # Table rows
    pdf.set_text_color(0, 0, 0)
    orig_sorted  = sorted(result.original_modules,     key=lambda m: m.module_id)
    recal_sorted = sorted(result.recalibrated_modules, key=lambda m: m.module_id)

    total_orig = total_recal = 0.0
    for i, (orig, recal) in enumerate(zip(orig_sorted, recal_sorted)):
        delta = recal.allocated_hours - orig.original_hours
        total_orig  += orig.original_hours
        total_recal += recal.allocated_hours
        fill = i % 2 == 0
        pdf.set_fill_color(238, 242, 247) if fill else pdf.set_fill_color(255, 255, 255)
        pdf.set_font("Helvetica", "", 9)
        row = [
            str(orig.module_id),
            orig.module_name[:22],
            f"{orig.original_hours:.2f}",
            f"{recal.allocated_hours:.2f}",
            f"{delta:+.2f}",
            f"{orig.pyq_score:.4f}",
            recal.difficulty.value[:4],
            recal.importance.value[:8],
        ]
        for w, val in zip(col_widths, row):
            pdf.cell(w, 7, val, border=1, fill=fill)
        pdf.ln()

    # Totals row
    pdf.set_font("Helvetica", "B", 9)
    pdf.set_fill_color(220, 220, 220)
    pdf.cell(col_widths[0] + col_widths[1], 7, "TOTAL", border=1, fill=True)
    pdf.cell(col_widths[2], 7, f"{total_orig:.2f}", border=1, fill=True)
    pdf.cell(col_widths[3], 7, f"{total_recal:.2f}", border=1, fill=True)
    for w in col_widths[4:]:
        pdf.cell(w, 7, "", border=1, fill=True)
    pdf.ln(10)

    # Warnings
    if result.warnings:
        pdf.set_font("Helvetica", "B", 11)
        pdf.cell(0, 8, "Warnings", ln=True)
        pdf.set_font("Helvetica", "", 9)
        for w in result.warnings:
            pdf.multi_cell(0, 6, f"  * {w}")

    pdf.output(out)
    print(f"[exporter] PDF -> {out}")
    return out


# ---------------------------------------------------------------------------
# DOCX
# ---------------------------------------------------------------------------

def export_docx(
    result: RedistributionResult,
    narrative: str = "",
    path: Optional[str] = None,
    output_dir: str = OUTPUT_DIR,
) -> str:
    try:
        from docx import Document
        from docx.shared import Pt, RGBColor, Inches
        from docx.enum.text import WD_ALIGN_PARAGRAPH
        from docx.oxml.ns import qn
        from docx.oxml import OxmlElement
    except ImportError:
        raise ImportError("python-docx is required: pip install python-docx")

    out = path or os.path.join(_ensure_output_dir(output_dir), "recalibrated_syllabus.docx")

    doc = Document()

    # Title
    title = doc.add_heading("Adaptive Syllabus Recalibration Report", level=0)
    title.alignment = WD_ALIGN_PARAGRAPH.CENTER

    # Narrative
    if narrative:
        doc.add_heading("Summary", level=1)
        para = doc.add_paragraph(narrative)
        para.style.font.size = Pt(11)

    # Table
    doc.add_heading("Recalibrated Module Hours", level=1)

    headers = [
        "#", "Module", "Original (h)", "Recalibrated (h)", "Delta",
        "PYQ Score", "Difficulty", "Importance"
    ]
    table = doc.add_table(rows=1, cols=len(headers))
    table.style = "Table Grid"

    # Header row
    hdr_row = table.rows[0].cells
    for i, h in enumerate(headers):
        hdr_row[i].text = h
        run = hdr_row[i].paragraphs[0].runs[0]
        run.bold = True
        run.font.color.rgb = RGBColor(0xFF, 0xFF, 0xFF)
        # Dark blue cell background
        tc = hdr_row[i]._tc
        tcPr = tc.get_or_add_tcPr()
        shd = OxmlElement("w:shd")
        shd.set(qn("w:fill"), "0F3460")
        shd.set(qn("w:color"), "auto")
        shd.set(qn("w:val"), "clear")
        tcPr.append(shd)

    orig_sorted  = sorted(result.original_modules,     key=lambda m: m.module_id)
    recal_sorted = sorted(result.recalibrated_modules, key=lambda m: m.module_id)

    total_orig  = 0.0
    total_recal = 0.0

    for orig, recal in zip(orig_sorted, recal_sorted):
        delta = recal.allocated_hours - orig.original_hours
        total_orig  += orig.original_hours
        total_recal += recal.allocated_hours

        delta_str = f"+{delta:.2f}h" if delta > 0.01 else (
            f"{delta:.2f}h" if delta < -0.01 else "—"
        )

        row = table.add_row().cells
        row[0].text = str(orig.module_id)
        row[1].text = orig.module_name
        row[2].text = f"{orig.original_hours:.2f}h"
        row[3].text = f"{recal.allocated_hours:.2f}h"
        row[4].text = delta_str
        row[5].text = f"{orig.pyq_score:.4f}"
        row[6].text = recal.difficulty.value
        row[7].text = recal.importance.value

    # Totals row
    tot_row = table.add_row().cells
    tot_row[0].text = ""
    tot_row[1].text = "TOTAL"
    tot_row[2].text = f"{total_orig:.2f}h"
    tot_row[3].text = f"{total_recal:.2f}h"
    for cell in tot_row:
        for para in cell.paragraphs:
            for run in para.runs:
                run.bold = True

    # Warnings
    if result.warnings:
        doc.add_heading("Warnings", level=1)
        for w in result.warnings:
            doc.add_paragraph(f"⚠ {w}", style="List Bullet")

    # Log
    if result.adjustment_log:
        doc.add_heading("Adjustment Log", level=1)
        for entry in result.adjustment_log:
            doc.add_paragraph(entry, style="List Bullet")

    doc.save(out)
    print(f"[exporter] DOCX → {out}")
    return out


# ---------------------------------------------------------------------------
# Convenience: export all formats
# ---------------------------------------------------------------------------

def export_all(
    result: RedistributionResult,
    narrative: str = "",
    formats: List[str] = None,
    output_dir: str = OUTPUT_DIR,
) -> dict:
    formats = formats or ["csv", "html", "docx"]
    paths = {}
    if "csv"  in formats: paths["csv"]  = export_csv(result, output_dir=output_dir)
    if "html" in formats: paths["html"] = export_html(result, narrative, output_dir=output_dir)
    if "pdf"  in formats: paths["pdf"]  = export_pdf(result, narrative, output_dir=output_dir)
    if "docx" in formats: paths["docx"] = export_docx(result, narrative, output_dir=output_dir)
    return paths